name: CC Commands Check

on:
  push:
    paths:
      - '.claude/cc-commands/**'
      - '.github/workflows/cc-commands-check.yml'
  pull_request:
    paths:
      - '.claude/cc-commands/**'
      - '.github/workflows/cc-commands-check.yml'

jobs:
  ci-check:
    name: CI Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          echo "::group::Installing ShellCheck"
          sudo apt-get update
          sudo apt-get install -y shellcheck
          echo "::endgroup::"

      - name: Run CI checks
        run: |
          echo "::group::Running comprehensive CI checks"
          cd .claude/cc-commands
          
          # Run ci.bash with verbose output for better debugging
          if bash .github/ci.bash -v; then
            echo "✅ All CI checks passed!"
          else
            echo "❌ CI checks failed!"
            exit 1
          fi
          echo "::endgroup::"

      - name: Upload CI results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-results
          path: |
            .claude/cc-commands/.github/ci.log
          retention-days: 7